export const GET_USERS = "GET_USERS";
export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_APPROVED_FOLLOWER= "ADD_APPROVED_FOLLOWER";
export const ADD_PENDING_FOLLOWER = "ADD_PENDING_FOLLOWER";
export const REMOVE_APPROVED_FOLLOWER = "REMOVE_APPROVED_FOLLOWER";
export const GET_REQUESTS = "GET_REQUESTS";

